name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-please:
    name: Run release-please
    runs-on: ubuntu-x64
    permissions:
      id-token: write
    outputs:
      release_created: ${{ steps.rp.outputs.release_created }}
      tag_name: ${{ steps.rp.outputs.tag_name }}
      sha: ${{ steps.rp.outputs.sha }}
      version: ${{ steps.rp.outputs.version }}
    steps:
      - id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@580590a644e82e79bb2598bdaba0be245a14dda0 # create-github-app-token/v0.2.2
        with:
          github_app: pyroscope-development-app

      - id: rp
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        with:
          token: ${{ steps.get-github-app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    name: Publish to PyPI
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-x64
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ needs.release-please.outputs.sha }}
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.12

      - name: Install pip build
        run: pip install build

      - name: Build wheel and sdist
        run: python -m build --sdist --wheel

      - name: Upload GitHub release artifacts
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ needs.release-please.outputs.tag_name }}
        run: gh release upload "$TAG_NAME" dist/* --clobber

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0

      - name: Publish GitHub release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ needs.release-please.outputs.tag_name }}
        run: gh release edit "$TAG_NAME" --draft=false
